### ISSUE TITLE
Quit the server with CTRL-BREAK. [12/Jun/2019 17:15:04] "POST /signup/doctor HTTP/1.1" 200 7330 [12/Jun/2019 17:15:09] "POST /signup/doctor HTTP/1.1" 200 7330 [12/Jun/2019 17:15:13] "GET /signup/doctor HTTP/1.1" 200 7082 [12/Jun/2019 17:15:15] "GET /signup/doctor HTTP/1.1" 200 7082 [12/Jun/2019 17:15:18] "GET /signup/doctor HTTP/1.1" 200 7082

### ISSUE THREAD

**Issue by asmat1** [apaar97/UpchaarWeb#4]

**Comment by apaar97** [comment]
No understandable issue title is mentioned. 
Please post the supporting stack trace, with the issue or error, separately.
Closing since the issue is unclear

**Comment by asmat1** [comment]
Aoa

Sir doctor sign-up  ni ho raha

**Comment by apaar97** [comment]
What error does it throw? You need to provide the corresponding error stack trace. It's difficult to debug without knowing the details.
